project:
  type: book

book:
  title: "Data Science for a Changing Planet"
  subtitle: "BI 349 | Fall 2023 | Saint Anselm College"
  author: "Shannon J. O'Leary"
  date: today 
  chapters:
    - index.qmd
    
    - part: A_hello-world.qmd
      chapters:
        - 01_intro-data-science.qmd
        - 02_install-R.qmd
        - 03_Rbasics.qmd
        - 04_Rproj.qmd

    - part: B_shark-wrangling.qmd
      chapters:
        - 05_data-management.qmd
        - 06_data-frames.qmd
        - 07_data-transformation-i.qmd
        - 08_data-transformation-ii.qmd
        - 09_tidy-data.qmd
        - 10_relational-data.qmd
        
    - part: C_bioinformatics-eDNA.qmd
      chapters:
        - 11_bioinformatics.qmd
        - 12_community-diversity.qmd
        
    - part: D_clim-change.qmd
      chapters: 
        - 13_greenhouse-gases.qmd
        - 14_impacts.qmd
        - 15_misinformation.qmd
        
    - part: E_natural-disasters.qmd
      chapters:
        - 16_exploratory-analysis-i.qmd
        - 17_exploratory-analysis-ii.qmd
        - 18_visualizations.qmd
        - 19_figure-types.qmd
        
    - part: F_reproducible-research.qmd
      chapters:
        - 20_reproducibility-crisis.qmd
        - 21_reproducibility-research.qmd
        - 22_research-compendium.qmd
        
    - part: G_phenology.qmd
      chapters:
        - 23_phenology.qmd
        - 24_phenology-modeling.qmd
        
    - part: H_air-pollution.qmd
      chapters:
        - 25_predictors.qmd
        - 26_linear-regression-model.qmd
        - 27_random-forest-model.qmd
        - 28_analyze-model-results.qmd
        
    - part: I_macrosystems-ecology.qmd
      chapters:
        - 29_thermal-structure-I.qmd
        - 30_thermal-structure-II.qmd
        - 31_elnino_I.qmd
        - 32_elnino_II.qmd
        
    - part: J_remote-sensing.qmd
      chapters:
        - 33_vegetation-I.qmd
        - 34_vegetation-II.qmd

    - part: z_appendix.qmd
      chapters:
        - z_references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 2
    toc-location: left
    code-fold: false
    code-overflow: scroll
    code-copy: hover
    number-sections: true
    anchor-sections: true
    embed-resources: true
  # pdf:
  #   documentclass: scrreprt

reference-location: margin
citation-location: margin
fig-cap-location: margin
tbl-cap-location: margin