# Scientific Misconduct | Reproducible Research {.unnumbered}

For each of our modules we will have a project-folder with an `Rproject`, `*.qmd`-files, and sub-directories for data, scripts, and results as described in our `Rproject` Tutorial. You should have a directory on your Desktop or Documents folder on your laptop (name it something like `bi349`) as a home directory for all of our project folders this semester. 

[Download the directory for this project here](https://drive.google.com/drive/folders/1Wl3pTfPoFMzVsT7Gd-c9RCKU1F4M1HqP?usp=sharing), make sure the directory is unzipped and move it to your `bi328` directory. You can open the `Rproj` for this module either by double clicking on it which will launch `Rstudio` or by opening `Rstudio` and then using `File > Open Project` or by clicking on the `Rproject` icon in the top right of your program window and selecting `Open Project`. 

Once you have opened a project you should see the project name in the top right corner^[Pro tip: If you run into issues where a quarto document won't render or file paths aren't working (especially if things were working previously) one of your first steps should be to double check that the correct `Rproj` is loaded.].

## Is science broken?

The so-called reproducibility crisis describes the fact that recent studies have found that particularly in psychology, social sciences, and the biomedical field many published studies cannot be reliably replicated or reproduced by other scientists. This lack of reproducibility suggests that the original findings may be unreliable and has raised concerns about the credibility and validity of scientific findings as a whole. Several causes contributed to the reproducibility crisis including favoring the publication of positive results over negative ones (publication bias), manipulating data analysis to achieve statistically significant results (p-hacking), running comparisons in large data sets until significant results are found (data dredging), or small sample sizes.The consequences of thes practices are far reaching as trust in science is undermined, resources are wasted on non-replicable findings, and the advancement of knowledge in certain fields is hindered, as well as other implications for policy and decision-making based on scientific findings. The scientific community has recognized the need to address the reproducibility crisis and efforts are being made to promote transparency in how methods and results are reported, for example through open science practices which emphasis sharing data and making research materials publicly available.


## Responsible Research is Reproducible Research

Reproducibility is a critical component of Responsible Conduct of Research (RCR) because it directly relates to the integrity and ethical conduct of scientific investigations as it encourages transparency in research. Scientists who make their methods, data, and analyses fully available to other facilitate accountability and enable scrutiny. This transparency is essential to maintaining the integrity of the research process which is a core principle of RCR. By allowing other researchers to independently verify and confirm the results of a study the credibility and trustworthiness of the research is reinforced and the integrity of the scientific process as a whole is maintained. When scientific studies an be successfully replicated and results are reproducible it reinforces the trust that society places in science and its ability to generate reliable and valid knowledge that can be used in policy and other decision-making processes.