{
  "hash": "4cfb9121cbf5ae3d03130890a9e79d66",
  "result": {
    "markdown": "\n# Bioinformatics\n\n\n\n\n\n**Learning Objectives**\n\nAfter completing this lab you should be able to \n\n* use `glue()` to paste strings into a file path (or other string).\n* use `pull()` to exract single values from a dataframe.\n* use inline code in documents to report results.\n* define genetic barcoding.\n* describe what metabarcoding is and how it can be applied to characterize biological communities.\n* compare and contrast Operational Taxonomic Units (OTUs) and Amplicon Sequence Variants (ASVs).\n* describe the general steps used to compile high-throughput sequence data into Amplicon Sequence Variants and outline how this is implemented in `DADA2`.\n* describe the general process of assigning ASVs to taxonomic groups and discuss potential problems that can arise \n\n\n[Download the directory for this project here](https://drive.google.com/drive/folders/1Zxltr7neJcLzU39emYpXyjpSArFgrh-l?usp=sharing), make sure the directory is unzipped and move it to your `bi328` directory. You can open the `Rproj` for this module either by double clicking on it which will launch `Rstudio` or by opening `Rstudio` and then using `File > Open Project` or by clicking on the `Rproject` icon in the top right of your program window and selecting `Open Project`. \n\nOnce you have opened a project you should see the project name in the top right corner^[Pro tip: If you run into issues where a quarto document won't render or file paths aren't working (especially if things were working previously) one of your first steps should be to double check that the correct `Rproj` is loaded.].\n\nThere should be a file named `11_bioinformatics.qmd` in that project directory. Use that file to work through this tutorial - you will hand in your rendered (\"knitted\") `quarto` file as your homework assignment. So, first thing in the `YAML` header, change the author to your name. You will use this `quarto` document to record your answers. Remember to use comments to annotate your code; at minimum you should have one comment per code set^[You should do this whether you are adding code yourself or using code from our manual, even if it isn't commented in the manual... especially when the code is already included for you, add comments to describe how the function works/what it does as we introduce it during the participatory coding session so you can refer back to it.] you may of course add as many comments as you need to be able to recall what you did. Similarly, take notes in the document as we discuss discussion/reflection questions but make sure that you go back and clean them up for \"public consumption\".\n\n::: {.column-margin}\n\nCRAN (Comprehensive R Archive) is the central archive for R packages. However, it is not uncommon for some packages there are specialized archives that are field specific. For example, [Bioconductor](https://bioconductor.org/install/) hosts many packages used for bioinformatics. After installing Bioconducter you can then install packages hosted there using `BiocManager::install()`.\n\nPreviously we have always called functions just using the function name. Given that you have loaded your packages, R automatically \"knows\" which package to call a function from. However, sometimes it might be helpful to specify which package a function is common from, either for documenting purposes (so that somebody else would know what library that function is from) or because sometimes there might be a function with the same name in more than one library and this way you can tell R explicitly which function you are calling.\n\n:::\n\nWe will need to install some new packages before we can get rolling. Execute the following commands to install them - note that the code chunk has the code chunk option `eval` set as `false` which means that when you render your quarto document it won't execute this code chunk and try to re-install these packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install Bioconductor\ninstall.packages(\"BiocManager\")\n\n# install dependency for data\nBiocManager::install(\"ShortRead\") \n\n# install dada2\nBiocManager::install(\"dada2\")\n\n# install Biostrings\nBiocManager::install(\"Biostrings\")\n\n# if these packages are not yet installed install patchwork and plotly \ninstall.packages(\"plotly\", \"patchwork\")\n```\n:::\n\n\nNow let's load our packages so we get started.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries ----\n\n# documentation\nlibrary(knitr)\n\n# eDNA analysis\nlibrary(dada2)\n\n\n# wrangling\nlibrary(tidyr)\nlibrary(dplyr)\nlibrary(tibble)\nlibrary(readr)\nlibrary(glue)\n\n# visualization\nlibrary(ggplot2)\nlibrary(ggthemes)\nlibrary(plotly)\nlibrary(patchwork)\n```\n:::\n\n\n## Next-generation sequence data enable metabarcoding to describe community composition\n\nHigh-throughput sequencing data, often referred to as next-generation sequencing (NGS) data, is a type of biological data generated through advanced sequencing technologies that allow for the rapid and simultaneous sequencing of a large number of DNA or RNA molecules. These technologies have revolutionized genomics, transcriptomics, and other related fields by enabling the efficient and cost-effective analysis of genetic material on a massive scale. There are various high-throughput sequencing platforms available, including Illumina, Ion Torrent, Pacific Biosciences (PacBio), Oxford Nanopore Technologies (ONT), and others. High-throughput sequencing has become more cost-effective over time, making it accessible to a broader range of researchers and enabling large-scale genomics projects. \n\nThe key difference between high-throughput sequencing platforms compared to traditional Sanger sequencing^[anger sequencing, also known as dideoxy sequencing or chain-termination sequencing, is a traditional DNA sequencing method that was developed by Frederick Sanger and his colleagues in the late 1970s. It was the primary method for DNA sequencing for several decades before the advent of high-throughput next-generation sequencing (NGS) technologies. Sanger sequencing is still used today for specific applications, such as sequencing individual genes or validating NGS results.] is that they are capable of simultaneously sequencing thousands to millions of DNA fragments or RNA molecules in a single sequencing run. This parallel processing greatly increases the speed and efficiency of sequencing compared to traditional Sanger sequencing.\n\nNGS platforms produce a vast amount of data. A single sequencing run can generate gigabytes to terabytes of raw sequencing data, depending on the instrument's capacity and the type of experiment being conducted^[ Don't worry, we are going to use a data set that consists of samples have been modified to reduce size but still preserve realistic sequence variation and errors to create small example data set that your laptops can handle.]. Typically, high-throughput sequencing generates short sequences, referred to as \"reads.\" The length of these reads can vary depending on the sequencing platform but is typically in the range of 50 to 300 base pairs. Usually you get one forward and one reverse read per sequenced template DNA.\n\nIn the context of metabarcoding of environmental DNA this means that we can use universal primers to amplify template DNA present in the environmental sample that potentially are from different organisms^[If you used Sanger sequencing you would just get a bunch of noise, because the sequencer would not be able to make a distinct base call for any position] because we can sequence all the amplified template DNA strands at once. \n\n## Bioinformatics pipelines are important tools to processing NGS data\n\nAnalyzing high-throughput sequencing data requires sophisticated bioinformatics tools and pipelines. Bioinformatics pipelines are widely used in genomics and related fields to streamline and standardize data analysis workflows. They comprise a series of structured and automated series of computational and data analysis steps designed to process and analyze biological data. Frequently, data takes on of several paths through the pipeline where the output from one step becomes the input for the next step. \n\nGenerally, a bioinformatics pipeline takes a specific type(s) or raw input data, such as DNA or RNA sequence data, frequently generated from high-throughput techniques. This data set then goes through the first stage of the pipeline where it is pre-processed for analysis steps, including quality control, data cleaning, and format conversion to ensure the data set is robust and meets a standardized format for downstream analysis. Pipelines frequently consists of a series of analysis steps or modules tailored to specific research questions/tasks, for example sequence alignment, variant calling, gene expression quantification, protein structure prediction.\n\nBecause pipelines are designed to allow for a high degree of automation to reduce error and maximize efficiency. Frequently, users use scripts or specific workflow management tools to execute each analysis step in a predefined errors. Because of this automation, it can be tempting to \"blackbox\" the analysis where an inexperienced user can run complex data analysis without understanding what is happening at each stage. However, for an analysis appropriate to a specific data set it is critical that scientists understand how to configure parameters and options for each analysis step to customize the pipeline for the specific data set and research objectives.\n\nBioinformatics tools are often run from the command line. Linux is frequently the operating system of choice^[You're laptop is likely MacOS or Windows and Linux would be the third common OS, however, it is not designed to be as user-friendly as Mac/Windows and has a steep learning curve.] as it provides a powerful and standardized command-line interface that makes it easy to automate tasks, write scripts, and integrate various tools into analysis pipelines. It also offers a high degree of customization and flexibility due to its open source nature^[This also means its free!]. In addition, it is known for its efficiency and stability which is critical when running resource-intensive analysis.\n\nHigh performance clusters allow for efficient handling of large data set by allowing multiple tasks to be executed in parallel^[Your laptop probably has two to four cores, which means you could run tasks in parallel on up to two threads. Many linux servers have upward of 20 threads to run things in parallel on, for high performance clusters (HPCs you may be looking at 100s)].\n\nDon't worry, you're not going to have to learn how to use a Linux Terminal. We will be using a pipeline that runs in `R`.\n\n`Dada2` [@callahanDADA2HighresolutionSample2016] is a bioinformatics pipeline which implements functions that can be used for the quality control, denoising, and analysis of amplicon sequencing data, particularly data generated from high-throughput sequencing technologies like Illumina's MiSeq or HiSeq platforms. It is widely used in microbiome research and is becoming increasingly popular for the analysis of environmental DNA (eDNA) metabarcoding data sets.\n\nThe key modules (steps) include\n\n1. **Quality Filtering**: DADA2 begins by assessing the quality of each sequence read in the dataset. Low-quality reads, which may contain sequencing errors or noise, are filtered out. This step helps improve the accuracy of downstream analysis.\n2. **Sequence Dereplication**: Identical sequences are collapsed into unique sequence variants (also known as amplicon sequence variants or ASVs). This step reduces redundancy in the dataset and accounts for potential PCR or sequencing errors.\n3. **Denoising**: DADA2 employs a statistical model to distinguish between true biological sequence variants and sequencing errors. By modeling the error profile of the sequencing data, it can identify and correct errors, resulting in more accurate sequence variants.\n4. **Chimera Removal**: DADA2 identifies and removes chimera sequences, which are artificial sequences generated during PCR that can lead to incorrect biological interpretations.\n5. **Phylogenetic Assignment**: After denoising, `DADA2` assigns taxonomy to the sequence variants by comparing them to reference databases, allowing researchers to identify the taxa present in the sample.\n\nIn contrast to other pipelines used to process metabarcoding data sets, `DADA2` generates ASVs.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Consider this\n\nExplain what the difference between an OTU and and ASV (include what each abbreviation stands for). You will want to revisit this question after having completed this tutorial and having a better understanding of the methods implemented in `DADA2`.\n\n:::\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\nEnough chit chat! Let's go!\n\n## Demultiplexing\n\nGenerally, multiple samples are pooled and run on the same NGS sequencing lane. The amplified sequences (amplicons) of each sample are tagged with the same unique molecular barcode or index. This means that the first step is to take the entire output of a sequencing run and demultiplex it, i.e. each sequence read is assigned back to its respective sample based on the barcode/index combination.\n\n::: {.column-margin}\n\n`FASTQ` files are a common file format used to store biological sequence data, particularly data generated by next-generation sequencing (NGS) technologies like Illumina sequencing platforms. In contrast to `FASTA` files which contain only sequence data, `FASTQ` files contain information about the sequences of DNA or RNA fragments, associated quality scores, and optional sequence identifiers.\n\n:::\n\n\nThis data set has already been demultiplexed and the individual `fastq` files are in your `data` folder.\n\n\n## Quality check and filter sequences \n\nIf you look in the `data` folder your project directory, you will see that you have a folder called `seq` that contains a folder for your raw sequences and also one that we will use to hold your sequences once we have done some quality filtering and trimming.\n\nBefore we get started we are going to create a series of vectors that contain our file paths and sample names that we can use throughout the analysis^[There are some key advantages to setting up vectors in this way. First, you only need to type in the information once, and then you can just call the vector which is a lot shorter and easier to type in. Second, you make the code more easily reusable for another analysis because you only need to change the file paths in one location and don't have to find all the spots in your code where the file path needs to be changed. Finally, as you will see you are working with a large number of individual files, so when we create sample names based on the file names we don't have to type them in all by hand which saves time and also minimizes the chances of typos.]. We are also going to extract the sample names and save them in a variable. We are able to do this because all of our filenames have a similar pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# designate file paths ----\n\n# create variable with initially trimmed reads\nraw <- \"data/seq/raw\"\n\n# path for filtered reads\nfilt <- \"data/seq/filt\"\n\n\n# create lists of matched forward & reverse fastq files ----\n\n# forward reads\nfnFs <- sort(list.files(raw, pattern = \"_R1.fastq\", full.names = TRUE))\n\n# reverse reads\nfnRs <- sort(list.files(raw, pattern = \"_R2.fastq\", full.names = TRUE))\n\n# create vector with sample names\nsample.names <- substr(basename(fnFs), 1, (nchar(fnFs)-25))\n\n\n# create file names & paths for filtered reads ----\n\n# named vectors of forward reads \nfiltFs <- file.path(filt, glue(\"{sample.names}_R1.fastq.gz\"))\nnames(filtFs) <- sample.names\n\n# named vectors of reverse reads \nfiltRs <- file.path(filt, glue(\"{sample.names}_R2.fastq.gz\"))\nnames(filtRs) <- sample.names\n```\n:::\n\n\nThere are 74 samples in the data set.\n\nNow that we have all of our file paths set up our next step is to take a look at the quality profile of the sequences. We could look at all of them, however, usually it is sufficient to spot check a few sequences to get an idea of what the quality looks like to give us an idea of what threshold values we should be using for quality filtering.\n\n`DADA2` has a built in function `plotQualityProfile()` that pulls the information from the `fastq` files which contains the quality information for each nucleotide call. Quality is measured as PHRED scores, a score of 40 should be interpreted as an expected 1 in 10,000 error rate, 20 would be a 1 in 100 chance of a base call being incorrect.\n\n::: {.column-margin}\n\nWe are wrapping the plotting function in `ggplotly()` which is built on the `plotly` package to generate interactive figures. It will take a second for your figure to pup up in the `Viewer` pane on the bottom left of `Rstudio`. If you hover over different points of the plot with your mouse you will see a little pop that lists the exact values.\n\n:::\n\nLet's go ahead an plot the quality sequence for the first sample We can do this by passing the first file path in the `fnFs` vector using `[1]` to indicate the first element of the vector.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplotly(plotQualityProfile(fnFs[1]))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Quality scores for the forward reads of the first sample. Grey-scale underlying heatmap shows frequency of each score at each base position (darker color is higher frequency), green line is em quality score for base position, orange lines indicate the quartiles (solid is median, dashed = 25th and 75th quartile). The red line indicates the percentage of reads that extend to at least that position.](11_bioinformatics_files/figure-html/fig-err-forw-1.png){#fig-err-forw width=672}\n:::\n:::\n\n\nAs you can see there is a lot going on in this figure. The x-axis indicates the cycle number which is equivalent to the base position in the sequence (one base call is added per cycle) while the y-axis indicates the quality score. In the bottom left you can see the number of reads (sequences) in the file indicated. You can see grey shading which is a heatmap indicating the frequency of each score at each position. Darker colors indicate that a certain quality score is more common at that position across all the reads in the sample. The green line is the mean quality score, orange lines are the quartiles. The read lines indicates the proportion of reads that extend to that position.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nGo ahead and plot the reverse reads for the 12th sample in the data set. Then describe the quality patterns you are seeing for your forward and reverse reads. You can use the table below that summarizes how to interpret the quality scores.\n\n:::\n\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n::: {.callout-tip collapse=true}\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplotly(plotQualityProfile(fnRs[12]))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Quality scores for the reverse reads in 12th sample. Grey-scale underlying heatmap shows frequency of each score at each base position (darker color is higher frequency), green line is median quality score for base position, orange lines indicate the quartiles (solid is median, dashed = 25th and 75th quartile). The red line indicates the percentage of reads that extend to at least that position.](11_bioinformatics_files/figure-html/fig-err-rev-1.png){#fig-err-rev width=672}\n:::\n:::\n\n\nReverse reads typically have lower quality and larger drop-off compared to forward reads. Trimming too conservatively can result in downstream issues when forward and reverse reads cannot be merged due to a lack of overlap.\n\n:::\n\n\n| **Quality score of base call** | **Confidence of base call being correct** |\n|--------------------------------|-------------------------------------------|\n| 10                             | 90                                        |\n| 20                             | 99                                        |\n| 30                             | 99.9                                      |\n| 40                             | 99.99                                     |\n\n\n## Trim sequences\n\nWe will use the information from the quality scores to make decision on appropriate threshold values to use to trim our sequences.\n\nWe are going to use a series of filters to remove low quality reads from the samples. Specifically, we will remove any basecalls that were too ambiguous to call,^[`N` are unknown nucleotides. If the signal for a base is too ambiguous to make a call, the Illumina platform will call it `N`. `DADA2` assumes there are no `NNN` in the data set so we have to remove them.] and any remaining PhiX reads still in the data set^[PhiX is a bacteriophage. It's DNA is spiked into libraries being sequenced to improve the quality sequencing run by increasing the sequence diversity]. Next, the first and last xx bases are trimmed for each read as these are usually low quality. Additionally, reads are truncated at first instance of a quality score < 6. Finally, reads < 35 bp after trimming are removed.\n\nWe are assuming matching order of forward and reverse reads for each sample.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nLook up the `filterAndTrim()` function and annotate each line of the code to indicate what each argument does, include both what the argument controls in general and then specifically what this means for this example.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter reads\nout <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, #\n                     truncLen = c(280, 280),     #\n                     trimLeft = c(18, 2),        #\n                     truncQ = 6,                 #\n                     maxEE = c(2,2),             #\n                     minLen = 35,                #\n                     rm.phix = TRUE,             #\n                     matchIDs = FALSE,           #\n                     compress = TRUE)            #\n```\n:::\n\n\n::: {.callout-tip collapse=true}\n\n## Pointers\n\nHere are descriptions of the key arguments that set thresholds for quality filters\n\n* `truncQ`: sets a minimum Q score. At the first instance of a quality score less than or equal to truncQ, the sequence is truncated.\n* `truncLen`: sets the length at which the sequences will be truncated. Sequences shorter than the length are eliminated.\n* `trimLeft`: sets the length that will be removed on the 5’ side of the reads. This allows you to remove the primers if it has not been done beforehand^[Primers used are ITS3_KYO2: GATGAAGAACGYAGYRAA = 18bp\nITS4: TCCTCCGCTTATTGATATGC = 20b].\n* `maxEE`: sets the maximum number of “expected errors” allowed in a read. This filter is based on the Q index. The more the number is increased, the less strict we are.\n\n:::\n\nLet's take a look at what that function has done. We assigned the output to a variable called `out`. \n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nUse the functions `class()` and `head()` to get an idea of what type of object we have created and then briefly describe what information is contained in that object.\n\n:::\n\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n::: {.callout-tip collapse=true}\n\n## Solution\n\nWait - that function has created a matrix array (a type of object you could describe as a multidimensional vector or a poor man's data frame) that tells us how many reads per sample went into a the filters and then who many came out. \n\nBut where did our filtered reads go? Remember, we gave the function the file paths for both the input files (`data/seq/raw/*.fastq.gz`) and where to write the filtered files and what to name them (`data/seq/fil/*.fastq.gz`). If you use the file navigation pane you should see that it now contains those files.\n\nThe object we created that is now in our environment holds the record of what occurred during filtering. It is very common that bioinformatics pipelines generate output files at various steps that let the user track what is happening that can be used to ensure everything is going as expected and also allow them to pick up on unusual patterns that might be indicative of the fact that your threshold values might not be appropriate, that there is something odd going on with the data, or that perhaps commands where not properly formulated and therefore didn't take place the way the researcher expected them to.\n\n:::\n\n\nLet's take a look to see how many reads where removed from the data set.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nThis code chunk converts the matrix into a dataframe. Use your coding skills to create a new column called `perc_lost` that contains the percent of reads that were lost in this filtering step. Then calculate the mean and standard deviation of the percent reads lost and the mean and standard deviation of the number of reads that remain per sample.\n\nThen use `kable()` to display your function in the console/your rendered html report. \n\nNote the inline code below that is pulling the key pieces of information directly from your data frame. This can be really helpful because e.g. if you are rerunning code on an updated data set you would not have to dig through your output to make sure that you updated all the results, instead R can do that for you. You can indicate that it is inline code using backticks and then indicating the engine using `r`. You will see that notation through out this document.\n\nThe function `pull()` allows you to extract (pull) a single value from a column.\n\n:::\n\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summarize proportion of reads lost during trimming\ncheck <- as.data.frame(out) %>%\n```\n:::\n\n\n:::\n\n::: {.callout-tip collapse=true}\n\n## Solution\n\n\n::: {#tbl-filt-results .cell tbl-cap='Mean and standard deviation of the proportion of reads lost due to quality filtering and the mean and standard deviation of the number of remaining reads per sample post filtering.'}\n::: {.cell-output-display}\n| mean_loss| std_loss| mean_reads| std_reads|\n|---------:|--------:|----------:|---------:|\n|  49.05541| 8.624355|   509.4459|  86.24355|\n:::\n:::\n\n\n:::\n\nAfter quality trimming samples contain approx. 509% (+/- 86) reads. Quality trimming removed 49.1% (+/- 8.6%) reads from each sample.\n\nWe will track how many reads we \"lose\" at each step to understand how different steps affect the number of reads that remain in the sample.\n\nNext to knowing how many low quality reads where removed we will want to take a look at the quality of the remaining reads after we have trimmed.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nPlot the quality scores for the forward and reverse of one random sample and compare your results to the raw data. Make sure to add a figure caption using the code chunk options!\n\n:::\n\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n\n::: {.callout-tip collapse=true}\n\n## Solution\n\nThis is what the plot for your forward reads should look like.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Quality scores of forward reads for 16 random samples in the data set after trimming. Grey-scale underlying heatmap shows frequency of each score at each base position (darker color is higher frequency), green line is median quality score for base position, orange lines indicate the quartiles (solid is median, dashed = 25th and 75th quartile). The read line indicates the percentage of reads that extend to at least that position.](11_bioinformatics_files/figure-html/fig-err-for-fil-1.png){#fig-err-for-fil width=672}\n:::\n:::\n\n\nRemember to plot the reverse reads *for the same sample*.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Quality scores of reverse reads for 12 random samples in the data set after trimming. Grey-scale underlying heatmap shows frequency of each score at each base position (darker color is higher frequency), green line is median quality score for base position, orange lines indicate the quartiles (solid is median, dashed = 25th and 75th quartile). The read line indicates the percentage of reads that extend to at least that position.](11_bioinformatics_files/figure-html/fig-err-rev-fil-1.png){#fig-err-rev-fil width=672}\n:::\n:::\n\n\n:::\n\n## Generate error model\n\nNext, we need to be able to distinguish between error due to for example PCR or sequencing error and actual biological differences among sequences. We can train `DADA2` to be able to do this using a subset of our data as a training set using a machine learning approach to establish a parametric error model^[Note that the error rate is specific to a sequencing run] to estimate error rates.\n\nError rates are generally expected to drop with increased quality. By default 100 Million bases are used to generate the error model, this number can be increased for a better estimate.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nRun the code below to generate the error models. This will take a few seconds. While you wait, pull up the description of what this function does in the help pane and use comments to indicate what the function as a whole does and what the different arguments control.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# forward reads\nerrF <- learnErrors(filtFs,               # \n                    nbases = 1e8,         # \n                    multithread = FALSE)  # \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n9877138 total bases in 37699 reads from 74 samples will be used for learning the error rates.\n```\n:::\n\n```{.r .cell-code}\n# reverse reads\nerrR <- learnErrors(filtRs, \n                    nbases = 1e8,\n                    multithread = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n10480322 total bases in 37699 reads from 74 samples will be used for learning the error rates.\n```\n:::\n:::\n\n\n:::\n\nMachine learning estimates and observed values should show close overlap to indicate the quality (fit) of the model. The observed error rates should be consistent with the expected learned error rates for the 16 possible base transitions. If they do not, the number of bases used can be increased to allow the ML algorithm to train on a larger subset of the data. \n\nWe can use the function `dada2::plotErrors()` to compare the observed and estimated error plots as an indication of how good our error models are. We will plot both the forward and reverse error model and assign those to objects so we can use the `patchwork` package to plot them next to each other in a single plot^[the package `patchwork` allows us to combine multiple plots in one file. You can [read up on the basic layout options using `+`, `\\` and `|` here](https://patchwork.data-imaginist.com/articles/guides/assembly.html) and more a [sneak peak of more complex layouts here ](https://patchwork.data-imaginist.com/articles/guides/layout.html)].\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize estimated error\np1 <- plotErrors(errF, nominalQ = TRUE)\n\np2 <- plotErrors(errR, nominalQ = TRUE)\n\np1 / p2\n```\n\n::: {.cell-output-display}\n![Error rates for each possible transition for forward (top) and reverse reads (bottom). Observed (grey points) and estimated (black line) error rates for each consensus quality score. Expected error rates for nominal definition of the quality score are in red.](11_bioinformatics_files/figure-html/fig-err-rates-1.png){#fig-err-rates width=672}\n:::\n:::\n\n\n::: {.column-margin}\n\nThe plot will pop up in the Plot pane. You can change the size of the pane to resize and make it larger, it can also be helpful to use the `zoom` button to create a popout window for an even better look.\n\nNote also that you can use the code chunk option `fig-height:` to control the size in your rendered html output file.\n\n:::\n\nAs you can see this creates a series of plots - one for each possible transition e.g. the error frequency for an A being mistakenly called a C (`A2C`) etc. The black points are the observed error rates for each consensus quality scores. The black line is the estimated error rate after the model has converged. The red line indicates the expected error rates under the nominal definition of the Q-value for Illumina technology. \n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Consider this\n\nUse the figures to briefly describe how well our error models capture the observed data and how this compares to the expected error rates.\n\n:::\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n\n# Infer amplicon sequence variants (ASVs) and create sequence table\n\n`DADA2` uses exact variants instead of OTUs (operational taxonomic units)^[An OTU us a cluster of DNA sequences considered to belong to the same taxonomic unit based on a predefined sequence similarity threshold. By contrast, an ASV is a unique sequence variant obtained from raw, high resolution sequence data, there is no clustering based on similarity. As a result, multiple ASVs (haplotypes) may correspond to the same species.]. The pipeline infers ASVs from the set of reads by incorporating the census quality profiles and abundances of each unique sequence to determine whether a given sequence is more likely a true biological sequence or more likely spurious [@callahan_dada2_2016, @rosen_denoising_2012]. \n\nRunning this step on all samples at the same time is computationally more intensive than running the pipeline one sample at a time but increases the functions ability to resolve low-abundance ASV, including singletons.\n\n\n## Dereplicate, infer, and merge ASVs\n\nNow we are ready to identify the ASVs present in our data set.\n\nThe first step to do this is dereplication, which means that we are collapsing all identical reads into a set of unique sequences. Dereplicating or denoising data is an important step in amplicon processing workflows, instead of keeping all identical sequences only one is kept for processing and the number of sequences represented is stored a long with it. A new consensus quality score profile is calculated for each unique sequence based on the average quality score of each base for all sequences that are replicates of that given amplicon. These quality profiles Dereplication makes downstream processing a lot more efficient and less memory intense by eliminating redundant comparisons.\n\n::: {.column-margin}\n\nThe function `lapply()` is similar to a for loop, where it applies the same function to every file in the vector containing the filtered samples.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nderepFs <- lapply(filtFs,      \n                  derepFastq,      \n                  verbose = FALSE)  \n\nderepRs <- lapply(filtRs, \n                  derepFastq, \n                  verbose = FALSE)\n```\n:::\n\n\nIn the next step, sequence variants are inferred using the dereplicated data and the inferred error rates. Using the consensus quality profiles significantly increases `DADA2`'s accuracy.\n\n::: {.column-margin}\n\nAs we've mentioned previously, many metabarcoding pipelines use OTUs instead of ASVs. For OTU's reads that are at least 97% similar are clustered. There are two arguments for doing this, the first is many species have more than one haplotype for the same locus and so if you set the threshold for clustering at 100% you are oversplitting i.e. multiple unique sequences can \"belong\" to the same species. The second is that sequences from the same species might end up with different sequences not because of true biological differences but because of errors in the process of PCR amplifying sequences or during sequencing. However, ASVs are not the same thing as OTUs with a 100% threshold for clustering, instead, `DADA2` uses the information from the quality profiles and the error models to distinguish true biological differences that separate unique amplicons vs amplicons that are only different due to errors (i.e. base differences are artifacts).\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadaFs <- dada(derepFs,            \n               err = errF,         \n               selfConsist = FALSE,\n               multithread = TRUE) \n\ndadaRs <- dada(derepRs,\n               err = errR,\n               selfConsist = FALSE,\n               multithread = TRUE)\n```\n:::\n\n\n::: {.column-margin}\n\nDifferent sequence platforms and sequencing kits are limited by how long the reads can be. For example, this data set was sequenced on a 2x300bp Miseq platform. This means that each amplicon was sequenced 300 bp in the 5' to 3' direction and then 300bp in the 3' to 5' direction. This means that we can sequence inserts longer than 300 bp and merging the two strands (forward and reverse reads) increase the confidence in the reliability of the sequence in the overlapped region.\n\n:::\n\nOur last step is that we need to merge our forward and reverse reads to reconstruct the full target amplicon. \nForward and reverse-complement of corresponding reverse sequences are aligned and merging requires an overlap of 12 sequences and there are no mismatches permitted in the overlapping region. Paired reads that do not exactly overlap are removed to reduce spurious output.\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nLook up the `mergePairs()` function in the help pane and comment the code below to indicate what the function as a whole and each argument does.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmergeASVs <- mergePairs(dadaFs, filtFs, \n                        dadaRs, filtRs,\n                        minOverlap = 12,  \n                        maxMismatch = 0)\n```\n:::\n\n\n:::\n\nWe can take a look at the results. The function returns a list^[Remember, we can think of a list as an object that is like a shelf where each shelf holds one element in this case each sample is an element]. Let's take a look at the first element.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mergeASVs[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$S1\n                                                                                                                                                                                                                                                                                                                                                                                                            sequence\n1             ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTTGCGCCCCTTGGTATTCCGAGGGGCACACCCGTTTGAGTGTCGTGAATACTCTCAACCTTCTTGGTTTCTTTGACCACGAAGGCTTGGACTTTGGAGGTTTTTCTTGCTGGCCTCTTTAGAAGCCAGCTCCTCCTAAATGAATGGGTGGGGTCCGCTTTGCTGATCCTCGACGTGATAAGCATCTCTTCTACGTCTCAGTGTCAGCTCGGAACCCCGCTTTCCAACCGTCTTTGGACAAAGACAATGTTCGAGTTGCGACTCGACCTTACAAACCTTGACCTCAAATCGGGTGAGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n2                                                                                             ATGCGATAAGTAGTGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCCTTGGTATCCCGAGGGGCATGCCTGTTCGAGCGTCATTTCACCACTCAAGCCTGGCTTGGTGTTGGGCGACGTCCCCTTTTGGGGACGCGTCTCGAAACGCTCGGCGGCGTGGCACCGGCTTTAAGCGTAGCAGAATCTTTCGCTTTGAAAGTCGGGGCCCCGTCTGCCGGAAGACCTACTCGCAAGGTTGACCTCGGATCAGGCAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n3                                                                                                 ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCCTTGGTATTCCGAGGGGCATGCCTGTTCGAGCGTCATTATAACCACTCAAGCCCCGGCTTGGTCTTGGGGTTCGCGGTCCGCGGCCCTTAAACTCAGTGGCGGTGCCGTCTGGCTCTAAGCGCAGTAATTCTCTCGCTATAGTGTCTAGGTGGTTGCTTGCCATAATCCCCCAATTTTTTACGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n4                                          ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCACTCCTTGGTATTCCGAGGAGTATGCCTGTTTCAGTATCATGAGCACTCTCACACCTAACCTTTGGGTTTATGGCGTGGAATTGGAATGCGCCGACTGTCATGGTTGGCCCTTCTAAAATGTAGTTCTTGGCTGTCACCTAATACAGCAGTTTGGCCTAATAGTTTTGGCATTCATTGTCAAATCTTTGGCTAACATTTGCTCCAGGAGTCAGTCTTGATAATACAGAAAACTCATTCAAATTTTGATCTGAAATCAGGTAGGGCTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n5          ATGCGATACGTAATGTGAATTGCAGAATTCCGTGAATCATTGAATCTTTGAACGCATCTTGCGCCTCTTGGTATTCCGAGGGGCATGCCTGTTTGAGTGTCATTAGAACTATCAAAAAAATAGATGATTTCAATCGTTAATTTTTTTGGAATTGGAGGTGGTGCTGGTCTTTTTCCATTAATGGCCCAAGCTCCTCCGAAATGCATTAGCGAATGCAGTGCACTTTTTCTCCTTGCTTTTTCTGGGCATTGATAGTTTACTCTCATGCCCTAAGCTGGTAGGGAGGAAGTCACAGAATGCTTCCCGCTCCTGAATGTAATACAAAACTTGACGATCAAACCCCTCAAATCAGGCAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n7                                                                                 ATGCGATAAGTAATGCGAATTGCAGAATTCAGTGAGTCATCGAATCTTTGAACGCATATTGCGCCCTTTGGTATTCCGAAGGGCATGCCTGTTCGAGCGTCATGATCAACCATCAAGCCTGGCTTGTCGTTGGACCCTGTTGTCTCTGGGCGACAGGTCCGAAAGATAATGACGGTGTCATGGCAACCCCGAATGCAACGAGCTTTTTTATAGGCACGCATTTAGTGGTTGGCAAGGCCCCCTCGTGCGTTATTATTTTCTTACGGTTGACCTCGGATCAGGTAGGAATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n8                                                                                            ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCCTTGGTATTCCGAGGGGCATGCCTGTTCGAGCGTCATTGCAACCCTCAAGCATTGCTTGGTATTGGGCTCCGCTGCTCACCCAGCGGGCCTTAAAATCAGTGGCGGTGCCGTCGAGGCCCTGAGCGTAGTAAATATCCTCGCTATAGGGACTCGGTGGACGCTGGCCATTAACCCCCAACTTTCTAAGTTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n9                                                                                            ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCACCCTCTGGTATTCCAGGGGGTATGCCTGTTCGAGCGTCATTACAACCCTCAAGCACTGCTTGGTATTGGATGTCAACCATTGGTGGTGCATCTCAAAAGTATTGGCAGTAGCATTTAGCTTCTAGTGTAGTAAATTTCTCGCTTTGGAGTCAAGTGTCTAATTGCTAGATAGAACCCCTAATTTATCAAAGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n10                                                                                                   ATGCGATAAGTAATGCGAATTGCAGAATTCAGTGAGTCATCGAATCTTTGAACGCACATTGCGCCCTGTGGTATTCCGCAGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCTCTGCTTGGTGTTGGGCCCCGCCCGCTCGCGGCCGGCCCTAAAGACAGTGGCGGCAGCGTCTGGCTCCAAGCGTAGTACAATCCTCGCTCTGGTGCTAGGCGGTGGCCTGCCAGAACCCCCCTTCTATGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n11                                                                                               ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCACCTTCTGGTATTCTGGGAGGTATGCCTGTTCGAGCGTCATTGCAACCATCAAGCCTAGGCTTGGTATTGGATGCCACCGCTTGGTGCATTTCAAAATTAGTGGCGGTGCCATTCAGCTTCAAGCGTAGTAAATTTCTCGCTCCTGGAGTTTGTATGTTGTCTGCTAGAACCCCCTAATTTATCAAGGTTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n12                                                                                                                       GCGCGATAGGTATTGTGAATTGCAGAATTGTGAATCATCGAATTTTTGAACGCACATTGCACCCATTGGTATTCCGATGGGTATACTTGTTTGAGCGTCATTTCATTCTCCTTTTGGGTTTTGGCATGAATATTTCTTGCTGAATTATAATGGTGTGGCTACCAGACTACAACGTGATAGATATTTCGTTGGATGTGACTGGGATTGCTCACCTTAAAAACATTGTATAGACCTCAAATCAAGCAGGATTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n13 ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCATATTGCGCTCTTTGGTATTCCGAAGAGCATGCTTGTTTGAGTATCAGTAAACACCTCAACCTCCTCTTGTTTTTTCAAAAGGAGGGTGGACTTGAGCTATCCCAACAACCTTCACCGGTAGGCGGGCGGCTTGAAATGCAGGTGCAGCTGGACTTTTATCTGAGCTAAAAGCATATCTATTTAGTCCTCGTCAAACAGGATTATTACTATTGCTGCAGCTAACATAAAGGATAATTGTCCTCATTGCTGACTGATGCAGGATTTTACGACACTTTATGTGTTGTTCAACTCGATCTCAAATCAAGTAAGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n14                                                                             ATGCGATAAGTAATGCGAATTGCAGAATTCAGTGAGTCATCGAATCTTTGAACGCATATTGCGCCCTTTGGTATTCCGAAGGGCATGCCTGTTCGAGCGTCATTATCAACCATCAAGCCTGGCTTGTCGTTGGACCTCTTTGCCAATGAAATATGTGGCAGGTCCGAAAGATAATGACGGCGTCGTGTTTGACCCTAGATGCAACGAGCTTTTTATAGCACGCATTGATGTGGTCGGGCGACCCAGTCTTTAACCATTATTTTCTAAGGTTGACCTCGGATCAGGTAGGAATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n15                                                                                 ATGCGATAAGTAGTGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCTCCTGGTATTCCGGGAGGCATGCCTGTTCGAGCGTCATTAAAGACCACTCAAGCGATTTTGCTTGGTATTGGAAGAAGAGTGCCTCTGGCCCTCCCTTCCGAAATCCAATGGCGGAAAGTCTCACGTGCCCCGGCGTAGTAAGTTTATCTTTCGCTTGGACCCTGAGGCGTTCTCGCCCTCAAATCCCCAATACTATAGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n16                TTGCGATATGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCATATTGCACCCTCTGGTCCATTCCAGAGGGTATGCCTGTTTGAGTGTCATTAATGTATCAAACCACCAAGCTTGCTTGGTTGGTCTTGGATGTTGAGGGTTGCTGGGGTTATAATGATCAGCTCCCTTTAAATGCATTAGCTTGGAATGTATAAGCCATTTTAGCTTAGGCTGATATGAATACAGCGTATTAAATGCTTTTGCTAAAGTGTAGCTTGTCTGGGCTTATAACTGTCTCTAGCTGAGACTGTCTTTTGACATTGTTAAATCATGATCATGACCTCAAATCAGGTAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n17                                TTGCGATATGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTTGCACCCTTTGGTATTCCGAAGGGTATGCCTGTTTGAGTGTCATTAAATTCTCAACTTCAAATTGAATTTTGAAGCTTGGACTTTGGAGGTTTGCTGGTGTCACTATCGGCTCCTCTTAAATTCATTAGCGGAACTGTAAGGACCGGCTTTGGTTTGATAGCTAACATTATCTATGCCGTTGCTGTGACCTTTGTGTTTGGCTTCTAATGGTCATTTTGTTGACTGTCTCTGCTTTGAGGCATACACTTTTAAGCTTGACCTCAAATCAGGTAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n18                                                                                                    ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCGGTGGTATTCCGCCGGGCATGCCTATTCGAGCGTCATTACAACCCTCACGCCCCGCGTGGTCTTGGGCCGAGCCCCCCGGGCTGGCCTCAAAAGCAGTGGCGGTGCCTCTGGGTCCTGAGCGTAGTAACACTTCCGCTACAGGGCTCCCGAGCGTGCTGGCCGAACCCCAACCCTTCAGGTTGACCTCGGATTAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n19                                                                                  ATGCGATAAGTAATGCGAATTGCAGAATTCAGTGAGTCATCGAATCTTTGAACGCATATTGCGCCCTTTGGTATTCCGAAGGGCATGCCTGTTCGAGCGTCATTATCACAGTATCAAGCTTGGCTTGTCGTTGGGCCCTTTGTCACCTGGTGACAGGTCCCAAAGAGAATGACTGGTGTCGTAAAGACTCTAAATGCAACGAGCTTATAACAGCACGCATCTAGTAGTAATATGGCCCGGTTCTCACCTCTTTATTTCTCAAGGTTGACCTCGGATCAGGTAGGAATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n21                                                                                            ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCCTTGGTATTCCGAGGGGCATGCCTGTTCGAGCGTCATTACAACCCTCAAGCAATGCTTGGTGTTGGGCCGCGCCGCTAACCCGGCGGGCCCTAAAACCAGTGGCGGTGCCGTCGGGCTCTGAGCGTAGTAATTCTTCTCGCTATAGAGCCCCGGCGGATGCTAGCCAGCAACCCCCAATTTTCTATGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n22     ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTTGCGCTCTTTGGTATTCCGAAGAGCATGCCTGTTTGAGTGTCATGAAAATATCAACCTTGACTTGGGTTTAGTGCTCTTGTCTTGGCTTGGATTTGGCTGTTTGCCGCTCGAAAGAGTCGGCTCAGCTTAAAAGTATTAGCTGGATCTGTCTTTGAGACTTGGTTTGACTTGGCGTAATAAGTTATTTCGCTGAGGACAATCTTCGGATTGGCCGAGTTTCTGGGACGTTTGTCCGCTTTCTAATACAAGTTCTAGCTTGCTAGACATGACTTTTTTATTATCTGGCCTCAAATCAGGTAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n23                                                                                                    ATGCGATAAGTAATGCGAATTGCAGAATTCAGTGAGTCATCGAATCTTTGAACGCACATTGCGCCCTGTGGTATTCCGCAGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCTCTGCTTGGTGTTGGGCCCCGCCCCCGTGGCCGGCCCCAAAGTCAGTGGCGGTGCCGTCCGGCTCTAAGCGTAGTACATCTCTCGCTCTAGGGTCCCGCGGTGGCCTGCCAGAACCCCAACTTCTATGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n24                                                                                                 ATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCTGTGGTATTCCGCAGGGCATGCCTGTTCGAGCGTCATTTAACCACTCAAGCCTAGCTTGGTATTGGGGCACGCGGTCTCGCGGCCCTTAAAATCAGTGGCGGCGCCGGTGGGCTCTAAGCGTAGTACATACTCCCGCTATAGAGTTCCCTCGGTGGCTCGCCAGAACCCCTAATTTTTACAGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n25                                           ATGCGATACGTAATGTGAATTGCAGATTCAGTGAATCATCGAATCTTTGAACGCATATTGCACTCTTTGGTATTCCGAAGAGTATGCCTGTTTCAGTATCATGAAAAACCTCACAAATTCAATTTTGGCTTTGTGGACTTGAGCATTTTGCGGCTTTGTTGCTGCTGGCTTAAAATATATTTCTTGGATAGCATATTATGGCTTTCGAAACTCGGCTTAATAGTTTTGGCTTTTGGTCAAATCTTTAGCTCTTTTCAAAGTCTTCAAGTTATTCAAAAGTTTTATACGAACACTTTCTCAATTTTGATCTGAAATCAGGTAGGATTACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n26                                                                                               CTGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCCTTGGTATTCCGGGGGGCATGCCTGTTCGAGCGTCACTTCAACCCTCAAGCTCTGCTTGGTGTTGGGCCCTGCCGGCGACGGCAGGCCTTAAAACCAGTGGCGGCGCCGCTGGGCCCTGAGCGTAGTAATACTCCTCGCTACTGGGCCCCAGCGGATGCCTGCCAGCAAACCCAACTTTCTATGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAGCATATCAATAAGCGGAG\n   abundance forward reverse nmatch nmismatch nindel prefer accept\n1        172       1       1    150         0      0      2   TRUE\n2         47       2       4    230         0      0      1   TRUE\n3         43       3       3    234         0      0      2   TRUE\n4         34       5       5    179         0      0      2   TRUE\n5         32       6       2    147         0      0      2   TRUE\n7         21       4       6    218         0      0      1   TRUE\n8         17       8       9    229         0      0      2   TRUE\n9         17       9       7    229         0      0      2   TRUE\n10        13       7      10    237         0      0      1   TRUE\n11        12      20      21    233         0      0      1   TRUE\n12        12      10       8    257         0      0      2   TRUE\n13        10      11      12    139         0      0      1   TRUE\n14         9      19      20    215         0      0      1   TRUE\n15         9      15      13    219         0      0      2   TRUE\n16         6      17      22    154         0      0      1   TRUE\n17         6      16      23    170         0      0      1   TRUE\n18         6      13      16    238         0      0      1   TRUE\n19         5      23      27    220         0      0      1   TRUE\n21         4      26      25    230         0      0      2   TRUE\n22         4      14      11    143         0      0      1   TRUE\n23         4      22      26    238         0      0      1   TRUE\n24         3      21      24    235         0      0      1   TRUE\n25         3      18      15    181         0      0      2   TRUE\n26         2      25      30    233         0      0      1   TRUE\n```\n:::\n:::\n\n\nThis contains a dataframe where for each sequence (ASV) in that sample we get information on what the sequence looks like, the number of reads corresponding to this forward/reverse combination (abundance) etc.\n\nFor example we can query the largest and smallest overlap like this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Largest overlap \nmax(mergeASVs[[1]]$nmatch) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 257\n```\n:::\n\n```{.r .cell-code}\n# Smallest overlap\nmin(mergeASVs[[1]]$nmatch) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 139\n```\n:::\n:::\n\n\n\n## Create a sequence table\n\nNow we have a fully denoised set of sequences that can be used to generate a sequence table for further analysis that contains the merged sequence, abundance and indices of forward and reverse sequence variants that were merged. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nseqtab <- makeSequenceTable(mergeASVs)\n```\n:::\n\n\nLet's take a quick look at what this data set looks like.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(seqtab)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  74 701\n```\n:::\n\n```{.r .cell-code}\nseqtab[,1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n S1 S10 S11 S12 S13 S14 S15 S16 S17 S18  S2 S20 S21 S22 S23 S24 S25 S26 S27 S28 \n  0 218   0   0 124   0  48   0   0   0   0   0   0   0   0   0   0   0   0   0 \nS29  S3 S30 S31 S33 S34 S35 S36 S37 S39  S4 S41 S42 S43 S44 S45 S46 S47 S48 S49 \n  0   0   0   0   0   0  19   0 148   0   0   0   0  70   0   0   0   0 113  32 \n S5 S50 S51 S52 S53 S54 S55 S56 S58 S59  S6 S60 S61 S62 S63 S64 S65 S66 S67 S68 \n  0   0   0  46   0 117   0   0   0   0   0   0   0   0   0   0   0   0   0   0 \nS69  S7 S72 S73 S74 S75 S76 S77 S78 S79  S8 S80 S81  S9 \n  0   0   0   0   0 234   0   0 109   0  43   0   0  40 \n```\n:::\n:::\n\n\nWe can see that it has 74 rows (each sample is a row) and 701 columns (each ASV is a row). If we print just the first column (ASV) you can see that the way a sequence table is organized is that for each sample the number of times an ASV is observed is recorded. \n\n\n## Remove chimeras\n\nThe `DADA2` algorithm accounts for indel errors and substitutions when inferring ASVs but before taxonomic assignment we also need to check for chimeras^[Chimeras are non-biological sequences were the left- and right segment of the merged sequence are from two or more parent sequences.]. `DADA2` identifies sequences that are likely chimeras by aligning each sequence with sets of sequences that were recovered in higher abundance and then determining if any lower-abundant sequences can be made by mixing left and right sequences from two of the more abundant ones.\n\nWe can use the function `removeBimeraDenovo()` to identify and remove Chimeras and then creating and updated sequence table.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseqtab.nochim <- removeBimeraDenovo(seqtab,\n                                    method = \"consensus\", \n                                    multithread = FALSE, \n                                    verbose = TRUE)\n```\n:::\n\n\nAfter removing chimeras, the data set consists of 700 unique sequences across 74 samples. \n\nEven though chimeric sequences can frequently make up a large part of sequence variants and therefore initially make the data set seem more variable than it is, overall once you account for abundance, they should only be a very small component of the merged sequence reads. Here 0.1 % of merged sequence variants are chimeras, though once you account for abundance of these variants, overall 99.9% of merged sequences are not chimeric.\n\nLet's take a look at the distribution of our non-chimeric ASV lengths.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of sequence length for merged ASVs. The red dotted line indicates sequences that are 100-105bp long. We are targeting a 106 bp amplicon and are using 2x150 bp sequencing. Primer sites are approx 25bp each. ](11_bioinformatics_files/figure-html/fig-seq-length-ASV-1.png){#fig-seq-length-ASV width=672}\n:::\n:::\n\n\n\n## Summary of read filtering & processing for QC\n\nAt this point, we will want to take a look at how many reads where lost at each step to determine if those patterns look as expected. We can pull that information from various output files by counting the reads and putting them all in a dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# custom function to get read numbers\ngetN <- function(x) sum(getUniques(x))\n\n# create data table with number of reads per sample at each step\ntrack <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergeASVs, getN), rowSums(seqtab.nochim)) %>%\n  as.data.frame() %>%\n  rownames_to_column(\"sample\") %>%\n  rename(trimmed = reads.out,\n         denoisedF = V3,\n         denoisedR = V4,\n         merged = V5,\n         rm_chimera = V6) %>%\n  pivot_longer(names_to = \"filter\", values_to = \"reads\", cols = 2:7) %>%\n  mutate(filter = ordered(filter, levels = c(\"reads.in\", \"trimmed\", \"denoisedF\", \"denoisedR\", \"merged\", \"rm_chimera\")),\n         k_reads = reads/1000)\n\n# plot distribution\nggplot(track, aes(x = filter, y = k_reads)) +\n  geom_boxplot(fill = \"darkorange\") +\n  labs(x = \"filter/processing step\", y = \"thousand reads per sample\") +\n  theme_standard\n```\n\n::: {.cell-output-display}\n![Comparison of change in the number of reads per sample at each filtering & processing stage. Red dotted line indicates targeted 150k reads per sample.](11_bioinformatics_files/figure-html/fig-change-n-reads-1.png){#fig-change-n-reads width=672}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Consider this\n\nTake a look at the boxplot and describe how the different processing steps have impacted the number of reads remaining in the data set.\n\nRemember that this is a modified data set where each sample has been subsampled to contain 1000 reads - normally that initial box describing the distribution of samples would be wider as different samples would contain different numbers of reads. Generally, researchers target > 75,000 - 150,000 reads per sample to make sure that all taxa present can be recovered in the data set.\n\n:::\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n\n::: {.callout-tip collapse=true}\n\n## Solution\n\nOutside of the initial filtering there should not be any steps at which a substantial amount of reads are lost, the majority of reads should merge. If this is not the case, then trimming is likely to conservative and should be revisited. Similarly, only a small proportion should be chimeric. If primers are not completely removed, ambiguous nucleotides can interfere during chimera ID and that step of quality filtering should be revisited.\n\n:::\n\n\n## Taxonomic classification for ASVs present in each sample.\n\nWe are now in the final stretch. Now that we have our ASVs and our sequence table the only thing that we still need to do is figure out which species (or other taxonomic groups) our ASVs correspond to. \n\nThis brings us to an important limitation of metabarcoding studies which is that our results are only ever as good as our reference database to which we can match our ASVs. \n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Consider this\n\nOur next step is to match the sequences to a list of sequences that have taxonomic information. In our case study this would be a sequenced fungi. Describe your expectations of the results - do you expect every ASV in the data set to find a match in the reference? What other issues could result in results being ambiguous?\n\n:::\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n`DADA2` has a built in function of a naive Bayesian classification menthod (`assignTaxonomy()`) that takes the sequences to be classified as the input along with a `fasta` file that contains the reference sequences^[`fasta` files consist of a header line that starts with `>` and can contain any information about the sequence and then the sequence itself is in the next line. A `multifasta` file can contain multiple sequences, the program using the file determines the start of a new sequence by the fact that it \"sees\" the `>` of the next header file.].\n\nDepending on the project, scientists will pull sequences available from public databases such as genbank or if you are working with species that do not have a lot of sequences available you would need to create your own database by sampling individuals representing the different species/taxonomic groups you expect to encounter and sequencing them. \n\nWe are using the [UNITE database of references](https://unite.ut.ee/repository.php) which is designed to gather available ITS sequences to identify Eukaryotes. \n\nRunning this function is going to take several minutes - depending on the speed of your computer. Note that this code has the chunk option `eval` set as false so that it won't run. Instead you can see that using the function `save()` I have writen the object out to your results folder. Then we can load it into your R environment in the next code chunk using `load()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxotab <- assignTaxonomy(seqtab.nochim,\n                          refFasta = \"data/sh_general_release_dynamic_25.07.2023.fasta\",\n                          minBoot = 50, \n                          multithread = FALSE)\n\nsave(taxotab, \n     file = \"results/taxotab.rds\")\n```\n:::\n\n\nWe can take a look at our results... there is a lot of information in this table so let's just pull the first 5 ASV's taxonomy without the ASV sequence for a better viewing experience.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load object into environment\nload(\"results/taxotab.rds\")\n\n# look at first 5 ASVs' taxonomy without the ASV sequence\nwrite.table(taxotab[1:5,], row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\"Kingdom\" \"Phylum\" \"Class\" \"Order\" \"Family\" \"Genus\" \"Species\"\n\"k__Plantae\" NA NA NA NA NA NA\n\"k__Fungi\" \"p__Basidiomycota\" \"c__Agaricomycetes\" \"o__Agaricales\" \"f__Tricholomataceae\" \"g__Mycena\" NA\n\"k__Fungi\" \"p__Mucoromycota\" \"c__Umbelopsidomycetes\" \"o__Umbelopsidales\" \"f__Umbelopsidaceae\" \"g__Umbelopsis\" \"s__dimorpha\"\n\"k__Fungi\" \"p__Ascomycota\" \"c__Sordariomycetes\" \"o__Xylariales\" \"f__Amphisphaeriaceae\" \"g__Polyscytalum\" \"s__algarvense\"\n\"k__Fungi\" \"p__Ascomycota\" \"c__Dothideomycetes\" \"o__Mytilinidales\" \"f__Gloniaceae\" \"g__Cenococcum\" \"s__geophilum\"\n```\n:::\n:::\n\n\nWe can also pull the unique species identified.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(unname(taxotab[,7])) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] NA                    \"s__dimorpha\"         \"s__algarvense\"      \n  [4] \"s__geophilum\"        \"s__flavescens\"       \"s__terricola\"       \n  [7] \"s__elongatum\"        \"s__punicea\"          \"s__sylvestris\"      \n [10] \"s__humilis\"          \"s__subvinosa\"        \"s__opacum\"          \n [13] \"s__abramsii\"         \"s__ericae\"           \"s__terminalis\"      \n [16] \"s__variata\"          \"s__rexiana\"          \"s__zollingeri\"      \n [19] \"s__deciduus\"         \"s__album\"            \"s__chlamydosporicum\"\n [22] \"s__saponaceum\"       \"s__rufescens\"        \"s__populi\"          \n [25] \"s__podzolica\"        \"s__reidii\"           \"s__asperellum\"      \n [28] \"s__microspora\"       \"s__simile\"           \"s__acicola\"         \n [31] \"s__subsulphurea\"     \"s__camphoratus\"      \"s__pseudozygospora\" \n [34] \"s__heterochroma\"     \"s__brunneoviolacea\"  \"s__verrucosa\"       \n [37] \"s__auratus\"          \"s__mutabilis\"        \"s__chlorophana\"     \n [40] \"s__fuckelii\"         \"s__miniata\"          \"s__lignicola\"       \n [43] \"s__pilicola\"         \"s__phyllophila\"      \"s__australis\"       \n [46] \"s__citrina\"          \"s__fragilis\"         \"s__conica\"          \n [49] \"s__lubrica\"          \"s__pygmaeum\"         \"s__isabellina\"      \n [52] \"s__var._bulbopilosa\" \"s__finlandica\"       \"s__echinulatum\"     \n [55] \"s__lacmus\"           \"s__trabinellum\"      \"s__reginae\"         \n [58] \"s__spadicea\"         \"s__myriocarpa\"       \"s__physaroides\"     \n [61] \"s__calyptrata\"       \"s__nigrella\"         \"s__carneum\"         \n [64] \"s__vagans\"           \"s__metachroides\"     \"s__fumosa\"          \n [67] \"s__cantharellus\"     \"s__laetior\"          \"s__fusiformis\"      \n [70] \"s__spirale\"          \"s__pullulans\"        \"s__crocea\"          \n [73] \"s__sublilacina\"      \"s__acerinum\"         \"s__macrocystis\"     \n [76] \"s__vrijmoediae\"      \"s__changbaiensis\"    \"s__cygneicollum\"    \n [79] \"s__hymenocystis\"     \"s__dioscoreae\"       \"s__alnicola\"        \n [82] \"s__difforme\"         \"s__bicolor\"          \"s__spurius\"         \n [85] \"s__griseoviride\"     \"s__rebaudengoi\"      \"s__rufum\"           \n [88] \"s__globulifera\"      \"s__skinneri\"         \"s__sindonia\"        \n [91] \"s__verhagenii\"       \"s__maius\"            \"s__anomalovelatus\"  \n [94] \"s__diversispora\"     \"s__fellea\"           \"s__splendens\"       \n [97] \"s__coccinea\"         \"s__nitrata\"          \"s__risigallina\"     \n[100] \"s__juniperi\"         \"s__columbetta\"       \"s__rhododendri\"     \n[103] \"s__cinereus\"         \"s__fusispora\"        \"s__scaurus\"         \n[106] \"s__soppittii\"        \"s__grovesii\"         \"s__atropurpureum\"   \n[109] \"s__renispora\"        \"s__pura\"             \"s__foliicola\"       \n[112] \"s__phaeococcinea\"    \"s__rosea\"            \"s__stuposa\"         \n[115] \"s__minima\"           \"s__atrovirens\"       \"s__canadensis\"      \n[118] \"s__silvestris\"       \"s__sepiacea\"         \"s__pyriforme\"       \n[121] \"s__bulbillosa\"       \"s__glutinosum\"       \"s__cylichnium\"      \n[124] \"s__aeria\"            \"s__veluwensis\"       \"s__epicalamia\"      \n[127] \"s__hyalina\"          \"s__cylindrica\"       \"s__miyabei\"         \n[130] \"s__terrestris\"       \"s__rimosissimus\"     \"s__acuta\"           \n[133] \"s__myxotrichoides\"   \"s__physodes\"         \"s__alpina\"          \n[136] \"s__fallax\"           \"s__fumosibrunneus\"   \"s__albicastaneus\"   \n[139] \"s__mors-panacis\"     \"s__glacialis\"        \"s__acerina\"         \n[142] \"s__flavidum\"         \"s__ocularis\"         \"s__exigua\"          \n[145] \"s__piceae\"           \"s__verzuoliana\"      \"s__alliacea\"        \n[148] \"s__entomopaga\"       \"s__hyalocuspica\"     \"s__umbrosum\"        \n[151] \"s__bombacina\"        \"s__boeremae\"         \"s__fortinii\"        \n[154] \"s__miyagiana\"       \n```\n:::\n:::\n\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Give it a whirl\n\nUse your coding skills to additionally pull the unique genera, families, and orders contained in the data set and describe our results.\n\n:::\n\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n## From the beginning ...\n\n::: {.callout-note icon=false}\n\n## {{< fa clipboard-question >}}   Consider this\n\nNow that we have been through all the steps of processing next generation sequencing data set in a metabarcoding processing pipeline go back over the entire process, make sure you have understand what the key steps are and then outline that process below. Be sure to list the key steps in an organized manner and describe what occurs at each step in 2-3 sentences.\n\n:::\n\n::: {.callout-important icon=false}\n\n## {{< fa pen >}}   Did it!\n\n[Your answer here]\n\n:::\n\n\n## Acknowledgements\n\nThis chapter borrows heavily from the original `DADA2` tutorial as well as Alexis Carteron & Simon Morvan's tutorial based on the subset sequences from [@carteronTemperateForestsDominated2021].\n",
    "supporting": [
      "11_bioinformatics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}